In [163]:
import pandas as pd
import numpy as np

file_path="/Users/irisvirus/Desktop/Becode/Python/Projects/immo_data_analysis/immo_eliza_scraping/utils/cleaned_dataset.csv"
df= pd.read_csv(file_path)

In [164]:
df.head()

,house_index,url,bedrooms,property_type,property_subtype,locality,postal_code,street,number,box,...,fireplaceCount,buildingState,garden,gardenSurface,pool,landSurface,livingArea,surfaceOfThePlot,typeOfSale,energy_rating
0,0,https://www.immoweb.be/en/classified/house/for...,4.0,HOUSE,HOUSE,Woluwe-Saint-Pierre,1150,Rue au Bois,85,NaN,...,0.0,TO_RENOVATE,1.0,170.0,0.0,270.0,180.0,270.0,NaN,NaN
1,1,https://www.immoweb.be/en/classified/apartment...,3.0,HOUSE,APARTMENT_BLOCK,Uccle,1180,Rue de Verrewinkel,38,NaN,...,0.0,TO_RENOVATE,1.0,100.0,0.0,177.0,195.0,177.0,NaN,NaN
2,2,https://www.immoweb.be/en/classified/villa/for...,10.0,HOUSE,VILLA,Corroy-le-Grand,1325,Rue du Warichet,12,NaN,...,0.0,AS_NEW,1.0,3752.0,0.0,3985.0,510.0,3985.0,NaN,NaN
3,3,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Saint-Nicolas,4420,Rue Voie des Vaux,262,NaN,...,0.0,AS_NEW,1.0,492.0,0.0,600.0,141.0,600.0,NaN,NaN
4,4,https://www.immoweb.be/en/classified/apartment...,3.0,APARTMENT,APARTMENT,Oostende,8400,Torhoutsesteenweg,278,301,...,0.0,GOOD,0.0,0.0,0.0,NaN,132.0,NaN,NaN,NaN

In [165]:
df.set_index("house_index",drop=True, inplace=True )

In [166]:
df.tail()

,url,bedrooms,property_type,property_subtype,locality,postal_code,street,number,box,kitchen,...,fireplaceCount,buildingState,garden,gardenSurface,pool,landSurface,livingArea,surfaceOfThePlot,typeOfSale,energy_rating
house_index,,,,,,,,,,,,,,,,,,,,,
19973,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Herselt,2230,Limberg,145,NaN,0.0,...,0.0,NaN,0.0,0.0,0.0,1503.0,NaN,1503.0,PublicSale,NaN
19974,https://www.immoweb.be/en/classified/house/for...,4.0,HOUSE,HOUSE,Roeselare,8800,Tuinstraat,15,NaN,0.0,...,0.0,AS_NEW,0.0,0.0,0.0,406.0,NaN,406.0,NaN,NaN
19975,https://www.immoweb.be/en/classified/house/for...,0.0,HOUSE,HOUSE,Ruddervoorde,8020,Groenhovestraat,3 A,NaN,0.0,...,0.0,GOOD,0.0,0.0,0.0,450.0,NaN,450.0,NaN,NaN
19976,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Izegem,8870,-,-,NaN,1.0,...,0.0,NaN,0.0,0.0,0.0,441.0,NaN,441.0,NaN,NaN
19977,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Kraainem,1950,Bosdallaan,38,NaN,1.0,...,0.0,NaN,0.0,0.0,0.0,1504.0,NaN,1504.0,PublicSale,NaN

In [167]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16308 entries, 0 to 19977
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   url               16307 non-null  object
 1   bedrooms          16307 non-null  float64
 2   property_type     16307 non-null  object
 3   property_subtype  16307 non-null  object
 4   locality          16307 non-null  object
 5   postal_code       16307 non-null  object
 6   street            15889 non-null  object
 7   number            15786 non-null  object
 8   box               5122 non-null   object
 9   kitchen           16307 non-null  float64
 10  facades           11726 non-null  float64
 11  price             16306 non-null  float64
 12  furnished         16307 non-null  float64
 13  terrace           16307 non-null  float64
 14  terraceSurface    11473 non-null  float64
 15  fireplace         16307 non-null  float64
 16  fireplaceCount    16307 non-null  float64
 17  buildingState     13516 non-null  object
 18  garden            16307 non-null  float64
 19  gardenSurface     16307 non-null  float64
 20  pool              16307 non-null  float64
 21  landSurface       9057 non-null   float64
 22  livingArea        15374 non-null  float64
 23  surfaceOfThePlot  9057 non-null   float64
 24  typeOfSale        3527 non-null   object
 25  energy_rating     0 non-null      float64
dtypes: float64(16), object(10)
memory usage: 3.4+ MB

In [168]:
df.postal_code.unique()

array(['1150', '1180', '1325', '4420', '8400', '9660', '3000', '1140',
       '1050', '1370', '1970', '8570', '2600', '1080', '2070', '2580',
       '1500', '9031', '2940', '9000', '8300', '6700', '4000', '4600',
       '9040', '9890', '9880', '4101', '9300', '9310', '2170', '2610',
       '9940', '1950', '4020', '2800', '6838', '4460', '9050', '4430',
       '1083', '1070', '9700', '8531', '9968', '1160', '9320', '8000',
       '6730', '1300', '1190', '3020', '2650', '9550', '2660', '9500',
       '9680', '8430', '4450', '2100', '1170', '1853', '9900', '9600',
       '9620', '2018', '2930', '1410', '1601', '8370', '2860', '1640',
       '1040', '2060', '9032', '3191', '2160', '9100', '1560', '2150',
       '8510', '1780', '4920', '2500', '2861', '2140', '9030', '8870',
       '1731', '3010', '9051', '2970', '8500', '9860', '4140', '3960',
       '4300', '2000', '9140', '3970', '9070', '8530', '4557', '8434',
       '9840', '1000', '8690', '1200', '4684', '2960', '2830', '8680',
       '9041', '2570', '4624', '9080', '8310', '1830', '8880', '3680',
       '8301', '9420', '9950', '1090', '2850', '1020', '2221', '7160',
       '1350', '8020', '9270', '3090', '6001', '6790', '6800', '3300',
       '9060', '8920', '9090', '8700', '8670', '1600', '9450', '9290',
       '3570', '1210', '9971', '2020', '2880', '9830', '8720', '8420',
       '1740', '1702', '1435', '8200', '1654', '2640', '3454', '8800',
       '3700', '9570', '3001', '1082', '4100', '4400', '4480', '4520',
       '6720', '7890', '3080', '8810', '1800', '3500', '8950', '2180',
       '9200', '3110', '4800', '2620', '7940', '1060', '1930', '1650',
       '2050', '1652', '9552', '9400', '6792', '9404', '8790', '9750',
       '6791', '4500', '2811', '3540', '9230', '2300', '2220', '9260',
       '4102', '7100', '9190', '8572', '9991', '2920', '9280', '6180',
       '9800', '4053', '8210', '9630', '1981', '9990', '2235', '3202',
       '1081', '1330', '8450', '9820', '3150', '1745', '4280', '9240',
       '8970', '1770', '4680', '3384', '2200', '9520', '4040', '8501',
       '9220', '1380', '9472', '1820', '1420', '6747', '3201', '3111',
       '7090', '8793', '1620', '8480', '2290', '5377', '1700', '5020',
       '9850', '2550', '1332', '8820', '2870', '5000', '1850', '8750',
       '5580', '1790', '1570', '1030', '9980', '3220', '3890', '1331',
       '8550', '8340', '4710', '9930', '8930', '6723', '3012', '8710',
       '2340', '1400', '2900', '3800', '1357', '9402', '9810', '3040',
       '1860', '4683', '1785', '3200', '4031', '4540', '4671', '8760',
       '5550', '5660', '9910', '1651', '4032', '9870', '9130', '8770',
       '6990', '3460', '2840', '6767', '8540', '9170', '7141', '2040',
       '7060', '1120', '5070', '9255', '3290', '9185', '1501', '7830',
       '9160', '3271', '9790', '8470', '6880', '1980', '2230', '3210',
       '9470', '1933', '3790', '2910', '2400', '6812', '8551', '8972',
       '9250', '7170', '6224', '6870', '8980', '1390', '1760', '4360',
       '4030', '4610', '4041', '9690', '6810', '2890', '1340', '9506',
       '8620', '6850', '3140', '1730', '2520', '3400', '4960', '6762',
       '5100', '9111', '4870', '2812', '6740', '6060', '3370', '6780',
       '3830', '1880', '3840', '5080', '5190', '2530', '3660', '9831',
       '6600', '6940', '6900', '2222', '7700', '1490', '2630', '1502',
       '8600', '1840', '3320', '6941', '3190', '3945', '3221', '9112',
       '6280', '1932', '7760', '4050', '2320', '9150', '9340', '4042',
       '4650', '6997', '1630', '8380', '6041', '2980', '2627', '4900',
       '4620', '2390', '9473', '8660', '3450', '4180', '4681', '8610',
       '3850', '4651', '4630', '1861', '6706', '2560', '8650', '8730',
       '5170', '4550', '5101', '3390', '1910', '4690', '1547', '4451',
       '2950', '4120', '4121', '8560', '7500', '4432', '6951', '8581',
       '4350', '1470', '5060', '8830', '3061', '8780', '1310', '4431',
       '8792', '4317', '6230', '1602', '4621', '4260', '4250', '5330',
       '6760', '3620', '8553', '9770', '2270', '1750', '2431', '4342',
       '1342', '9992', '4590', '8940', '7912', '2845', '1450', '8630',
       '2590', '4530', '5500', '3128', '3530', '3740', '9052', '7301',
       '3052', '8860', '3950', '3550', '3520', '4347', '8900', '9120',
       '8580', '2540', '6820', '6210', '2243', '7110', '4160', '4163',
       '2820', '3120', '7340', '6960', '1348', '9970', '3560', '4682',
       '1701', '2260', '8582', '8460', '4570', '9960', '2370', '5590',
       '3050', '1301', '8791', '8840', '3940', '6183', '6830', '8740',
       '1421', '3600', '9401', '2460', '6950', '6043', '6666', '7950',
       '6220', '8211', '8850', '5004', '5564', '1440', '4122', '7080',
       '8511', '5537', '3590', '2440', '6769', '1473', '1742', '3870',
       '3770', '6920', '7864', '2801', '7540', '6860', '5560', '6811',
       '1831', '1495', '1320', '8490', '1480', '1461', '7911', '3380',
       '4802', '1761', '1653', '7390', '4190', '2360', '5541', '8377',
       '3470', '3360', '7380', '3583', '6660', '6141', '3910', '2110',
       '6150', '1703', '5380', '1755', '4910', '2310', '7021', '6836',
       '4340', '1540', '9920', '7973', '6031', '5555', '4820', '2223',
       '9667', '3440', '8647', '4218', '5001', '3720', '5620', '6000',
       '4051', '6986', '5575', '7520', '6110', '5640', '4052', '6042',
       '2381', '3930', '8433', '3118', '7712', '6250', '1430', '5031',
       '1851', '5530', '3270', '6630', '3051', '8851', '3350', '4780',
       '4453', '9308', '2470', '6761', '7300', '7040', '6980', '7534',
       '4130', '4577', '7972', '6032', '8890', '7780', '3060', '3920',
       '3512', '6890', '3391', '1670', '4524 JM', '7330', '3510', '7000',
       '2380', '5002', '6670', '2430', '7850', '8640', '8520', '4287',
       '3545', '2321', '1852', '2328', '3294', '6690', '6971', '7750',
       '6211', '5542', '7012', '3404', '6010', '2350', '9042', '1982',
       '9982', '2450', '1341', '3670', '8573', '5621', '2250', '7140',
       '5310', '7860', '7800', '3401', '6200', '4141', '6987', '8755',
       '7034', '3798', '2280', '5030', '3581', '6724', '7070', '6061',
       '3630', '7900', '7120', '6953', '1460', '2382', '6030', '8432',
       '7011', '2323', '7131', '2490', '6929', '7782', '7740', '7022',
       '7387', '5540', '7020', '5150', '2547', '2240', '4970', '7640',
       '4840', '5680', '1367', '4801', '6542', '6840', '3971', '3580',
       '3130', '4890', '5670', '9931', '7033', '2322', '1428', '6120',
       '3832', '4730', '3078', '2480', '6824', '6040', '3293', '8421',
       '4633', '7600', '3070', '3980', '3511', '2990', '3665', '2275',
       '3690', '9451', '3900', '6540', '3724', '3990', '6240', '3053',
       '3650', '3472', '2330', '3054', '4950', '7822', '4560', '3212',
       '3071', '3806', '2030', '4670', '3582', '5360', '3501', '3891',
       '5644', nan, '7730', '7181', '4700', '6851', '6717', '7880',
       '8554', '4845', '3018', '7321', '4672', '4987', '4990', '7810',
       '5651', '6750', '1457', '4850', '9180', '9403', '1130', '6637',
       '6687', '4860', '6741', '8587', '7322', '4852', '6782', '6972',
       '5351', '3730', '5032', '6440', '3640', '7180', '7190', '4470',
       '7350', '4623', '1741', '7332', '6560', '8552', '1315', '8953',
       '1404', '5523', '7866', '4452', '9551', '4217', '9881', '4877',
       '5501', '7030', '5650', '6680', '5300', '6640', '9921', '9932',
       '7533', '7742', '6927', '7331', '3381', '6140', '7711', '5646',
       '5140', '7870', '5570', '3211', '7863', '6238', '6674', '6534',
       '2288', '6921', '7130', '4219', '4210', '5022', '4537', '7618',
       '4608', '4980', '6970', '4837', '5630', '4367', '5024', '4861',
       '6530', '3621', '7041', '4770', '2242', '8954', '4607', '9406',
       '5370', '7804', '7382', '2387', '7610', '1360', '6567', '7063',
       '7942', '7522', '6223', '7370', '7943', '6781', '4458', '5600',
       '7134', '6460', '1474', '8904', '7031', '8978', '6500', '7506',
       '9988', '5561', '8431', '5350', '7050', '7536', '7061', '9961',
       '6020', '6221', '4506 JH', '4506', '6044', '6182'], dtype=object)

In [169]:
extra =df[df["postal_code"] == "4506 JH"]
extra

,url,bedrooms,property_type,property_subtype,locality,postal_code,street,number,box,kitchen,...,fireplaceCount,buildingState,garden,gardenSurface,pool,landSurface,livingArea,surfaceOfThePlot,typeOfSale,energy_rating
house_index,,,,,,,,,,,,,,,,,,,,,
19835,https://www.immoweb.be/en/classified/apartment...,3.0,APARTMENT,APARTMENT,Cadzand,4506 JH,NaN,NaN,NaN,0.0,...,1.0,AS_NEW,0.0,0.0,1.0,NaN,178.0,NaN,NaN,NaN

In [170]:
extra2 = df.drop(df[df["postal_code"] == "4506 JH"].index)
extra2

,url,bedrooms,property_type,property_subtype,locality,postal_code,street,number,box,kitchen,...,fireplaceCount,buildingState,garden,gardenSurface,pool,landSurface,livingArea,surfaceOfThePlot,typeOfSale,energy_rating
house_index,,,,,,,,,,,,,,,,,,,,,
0,https://www.immoweb.be/en/classified/house/for...,4.0,HOUSE,HOUSE,Woluwe-Saint-Pierre,1150,Rue au Bois,85,NaN,1.0,...,0.0,TO_RENOVATE,1.0,170.0,0.0,270.0,180.0,270.0,NaN,NaN
1,https://www.immoweb.be/en/classified/apartment...,3.0,HOUSE,APARTMENT_BLOCK,Uccle,1180,Rue de Verrewinkel,38,NaN,1.0,...,0.0,TO_RENOVATE,1.0,100.0,0.0,177.0,195.0,177.0,NaN,NaN
2,https://www.immoweb.be/en/classified/villa/for...,10.0,HOUSE,VILLA,Corroy-le-Grand,1325,Rue du Warichet,12,NaN,1.0,...,0.0,AS_NEW,1.0,3752.0,0.0,3985.0,510.0,3985.0,NaN,NaN
3,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Saint-Nicolas,4420,Rue Voie des Vaux,262,NaN,1.0,...,0.0,AS_NEW,1.0,492.0,0.0,600.0,141.0,600.0,NaN,NaN
4,https://www.immoweb.be/en/classified/apartment...,3.0,APARTMENT,APARTMENT,Oostende,8400,Torhoutsesteenweg,278,301,1.0,...,0.0,GOOD,0.0,0.0,0.0,NaN,132.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19973,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Herselt,2230,Limberg,145,NaN,0.0,...,0.0,NaN,0.0,0.0,0.0,1503.0,NaN,1503.0,PublicSale,NaN
19974,https://www.immoweb.be/en/classified/house/for...,4.0,HOUSE,HOUSE,Roeselare,8800,Tuinstraat,15,NaN,0.0,...,0.0,AS_NEW,0.0,0.0,0.0,406.0,NaN,406.0,NaN,NaN
19975,https://www.immoweb.be/en/classified/house/for...,0.0,HOUSE,HOUSE,Ruddervoorde,8020,Groenhovestraat,3 A,NaN,0.0,...,0.0,GOOD,0.0,0.0,0.0,450.0,NaN,450.0,NaN,NaN
19976,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Izegem,8870,-,-,NaN,1.0,...,0.0,NaN,0.0,0.0,0.0,441.0,NaN,441.0,NaN,NaN
19977,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Kraainem,1950,Bosdallaan,38,NaN,1.0,...,0.0,NaN,0.0,0.0,0.0,1504.0,NaN,1504.0,PublicSale,NaN

In [171]:
df = df.drop(df[df["postal_code"] == "4506 JH"].index)

In [172]:
df.drop(19835)

KeyError: '[19835] not found in axis'

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16307 entries, 0 to 19977
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   url               16306 non-null  object
 1   bedrooms          16306 non-null  float64
 2   property_type     16306 non-null  object
 3   property_subtype  16306 non-null  object
 4   locality          16306 non-null  object
 5   postal_code       16306 non-null  object
 6   street            15889 non-null  object
 7   number            15786 non-null  object
 8   box               5122 non-null   object
 9   kitchen           16306 non-null  float64
 10  facades           11725 non-null  float64
 11  price             16305 non-null  float64
 12  furnished         16306 non-null  float64
 13  terrace           16306 non-null  float64
 14  terraceSurface    11472 non-null  float64
 15  fireplace         16306 non-null  float64
 16  fireplaceCount    16306 non-null  float64
 17  buildingState     13515 non-null  object
 18  garden            16306 non-null  float64
 19  gardenSurface     16306 non-null  float64
 20  pool              16306 non-null  float64
 21  landSurface       9057 non-null   float64
 22  livingArea        15373 non-null  float64
 23  surfaceOfThePlot  9057 non-null   float64
 24  typeOfSale        3527 non-null   object
 25  energy_rating     0 non-null      float64
dtypes: float64(16), object(10)
memory usage: 3.9+ MB

In [ ]:
df["price"].mean()

472951.0558111009

In [ ]:
df.bedrooms.unique()

array([  4.,   3.,  10.,   6.,   2.,   1.,   8.,   5.,   0.,   7.,  12.,
        11.,   9.,  20.,  30.,  18.,  14.,  16.,  17.,  34.,  nan,  13.,
       200.])

In [ ]:
df[df["bedrooms"] == "200"]

Empty DataFrame
Columns: [url, bedrooms, property_type, property_subtype, locality, postal_code, street, number, box, kitchen, facades, price, furnished, terrace, terraceSurface, fireplace, fireplaceCount, buildingState, garden, gardenSurface, pool, landSurface, livingArea, surfaceOfThePlot, typeOfSale, energy_rating]
Index: []

[0 rows x 26 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 19980 entries, 4 to 19978
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   bedrooms          19980 non-null  int64
 1   property_type     19980 non-null  object
 2   property_subtype  19980 non-null  object
 3   locality          19980 non-null  object
 4   postal_code       19980 non-null  object
 5   street            17308 non-null  object
 6   number            17183 non-null  object
 7   box               5435 non-null   object
 8   kitchen           19980 non-null  int64
 9   facades           14360 non-null  float64
 10  price             19979 non-null  float64
 11  furnished         19980 non-null  int64
 12  terrace           19980 non-null  int64
 13  terraceSurface    14103 non-null  float64
 14  fireplace         19980 non-null  int64
 15  fireplaceCount    19980 non-null  int64
 16  buildingState     16529 non-null  object
 17  garden            19980 non-null  int64
 18  gardenSurface     19980 non-null  int64
 19  pool              19980 non-null  int64
 20  landSurface       10872 non-null  float64
 21  livingArea        18856 non-null  float64
 22  surfaceOfThePlot  10872 non-null  float64
 23  typeOfSale        4120 non-null   object
dtypes: float64(6), int64(9), object(9)
memory usage: 3.8+ MB

In [ ]:
df.isnull()

,url,bedrooms,property_type,property_subtype,locality,postal_code,street,number,box,kitchen,...,fireplaceCount,buildingState,garden,gardenSurface,pool,landSurface,livingArea,surfaceOfThePlot,typeOfSale,energy_rating
house_index,,,,,,,,,,,,,,,,,,,,,
0,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19973,False,False,False,False,False,False,False,False,True,False,...,False,True,False,False,False,False,True,False,False,True
19974,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,True,True
19975,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,True,True
19976,False,False,False,False,False,False,False,False,True,False,...,False,True,False,False,False,False,True,False,True,True
19977,False,False,False,False,False,False,False,False,True,False,...,False,True,False,False,False,False,True,False,False,True

Most expensive house

In [ ]:
df[df["price"] == 10500000]

,url,bedrooms,property_type,property_subtype,locality,postal_code,street,number,box,kitchen,...,fireplaceCount,buildingState,garden,gardenSurface,pool,landSurface,livingArea,surfaceOfThePlot,typeOfSale,energy_rating
house_index,,,,,,,,,,,,,,,,,,,,,
18916,https://www.immoweb.be/en/classified/exception...,8.0,HOUSE,EXCEPTIONAL_PROPERTY,Kalmthout,2920,NaN,NaN,NaN,0.0,...,0.0,GOOD,0.0,0.0,1.0,63713.0,2139.0,63713.0,NaN,NaN

In [ ]:
df.postal_code.unique()

array(['1150', '1180', '1325', '4420', '8400', '9660', '3000', '1140',
       '1050', '1370', '1970', '8570', '2600', '1080', '2070', '2580',
       '1500', '9031', '2940', '9000', '8300', '6700', '4000', '4600',
       '9040', '9890', '9880', '4101', '9300', '9310', '2170', '2610',
       '9940', '1950', '4020', '2800', '6838', '4460', '9050', '4430',
       '1083', '1070', '9700', '8531', '9968', '1160', '9320', '8000',
       '6730', '1300', '1190', '3020', '2650', '9550', '2660', '9500',
       '9680', '8430', '4450', '2100', '1170', '1853', '9900', '9600',
       '9620', '2018', '2930', '1410', '1601', '8370', '2860', '1640',
       '1040', '2060', '9032', '3191', '2160', '9100', '1560', '2150',
       '8510', '1780', '4920', '2500', '2861', '2140', '9030', '8870',
       '1731', '3010', '9051', '2970', '8500', '9860', '4140', '3960',
       '4300', '2000', '9140', '3970', '9070', '8530', '4557', '8434',
       '9840', '1000', '8690', '1200', '4684', '2960', '2830', '8680',
       '9041', '2570', '4624', '9080', '8310', '1830', '8880', '3680',
       '8301', '9420', '9950', '1090', '2850', '1020', '2221', '7160',
       '1350', '8020', '9270', '3090', '6001', '6790', '6800', '3300',
       '9060', '8920', '9090', '8700', '8670', '1600', '9450', '9290',
       '3570', '1210', '9971', '2020', '2880', '9830', '8720', '8420',
       '1740', '1702', '1435', '8200', '1654', '2640', '3454', '8800',
       '3700', '9570', '3001', '1082', '4100', '4400', '4480', '4520',
       '6720', '7890', '3080', '8810', '1800', '3500', '8950', '2180',
       '9200', '3110', '4800', '2620', '7940', '1060', '1930', '1650',
       '2050', '1652', '9552', '9400', '6792', '9404', '8790', '9750',
       '6791', '4500', '2811', '3540', '9230', '2300', '2220', '9260',
       '4102', '7100', '9190', '8572', '9991', '2920', '9280', '6180',
       '9800', '4053', '8210', '9630', '1981', '9990', '2235', '3202',
       '1081', '1330', '8450', '9820', '3150', '1745', '4280', '9240',
       '8970', '1770', '4680', '3384', '2200', '9520', '4040', '8501',
       '9220', '1380', '9472', '1820', '1420', '6747', '3201', '3111',
       '7090', '8793', '1620', '8480', '2290', '5377', '1700', '5020',
       '9850', '2550', '1332', '8820', '2870', '5000', '1850', '8750',
       '5580', '1790', '1570', '1030', '9980', '3220', '3890', '1331',
       '8550', '8340', '4710', '9930', '8930', '6723', '3012', '8710',
       '2340', '1400', '2900', '3800', '1357', '9402', '9810', '3040',
       '1860', '4683', '1785', '3200', '4031', '4540', '4671', '8760',
       '5550', '5660', '9910', '1651', '4032', '9870', '9130', '8770',
       '6990', '3460', '2840', '6767', '8540', '9170', '7141', '2040',
       '7060', '1120', '5070', '9255', '3290', '9185', '1501', '7830',
       '9160', '3271', '9790', '8470', '6880', '1980', '2230', '3210',
       '9470', '1933', '3790', '2910', '2400', '6812', '8551', '8972',
       '9250', '7170', '6224', '6870', '8980', '1390', '1760', '4360',
       '4030', '4610', '4041', '9690', '6810', '2890', '1340', '9506',
       '8620', '6850', '3140', '1730', '2520', '3400', '4960', '6762',
       '5100', '9111', '4870', '2812', '6740', '6060', '3370', '6780',
       '3830', '1880', '3840', '5080', '5190', '2530', '3660', '9831',
       '6600', '6940', '6900', '2222', '7700', '1490', '2630', '1502',
       '8600', '1840', '3320', '6941', '3190', '3945', '3221', '9112',
       '6280', '1932', '7760', '4050', '2320', '9150', '9340', '4042',
       '4650', '6997', '1630', '8380', '6041', '2980', '2627', '4900',
       '4620', '2390', '9473', '8660', '3450', '4180', '4681', '8610',
       '3850', '4651', '4630', '1861', '6706', '2560', '8650', '8730',
       '5170', '4550', '5101', '3390', '1910', '4690', '1547', '4451',
       '2950', '4120', '4121', '8560', '7500', '4432', '6951', '8581',
       '4350', '1470', '5060', '8830', '3061', '8780', '1310', '4431',
       '8792', '4317', '6230', '1602', '4621', '4260', '4250', '5330',
       '6760', '3620', '8553', '9770', '2270', '1750', '2431', '4342',
       '1342', '9992', '4590', '8940', '7912', '2845', '1450', '8630',
       '2590', '4530', '5500', '3128', '3530', '3740', '9052', '7301',
       '3052', '8860', '3950', '3550', '3520', '4347', '8900', '9120',
       '8580', '2540', '6820', '6210', '2243', '7110', '4160', '4163',
       '2820', '3120', '7340', '6960', '1348', '9970', '3560', '4682',
       '1701', '2260', '8582', '8460', '4570', '9960', '2370', '5590',
       '3050', '1301', '8791', '8840', '3940', '6183', '6830', '8740',
       '1421', '3600', '9401', '2460', '6950', '6043', '6666', '7950',
       '6220', '8211', '8850', '5004', '5564', '1440', '4122', '7080',
       '8511', '5537', '3590', '2440', '6769', '1473', '1742', '3870',
       '3770', '6920', '7864', '2801', '7540', '6860', '5560', '6811',
       '1831', '1495', '1320', '8490', '1480', '1461', '7911', '3380',
       '4802', '1761', '1653', '7390', '4190', '2360', '5541', '8377',
       '3470', '3360', '7380', '3583', '6660', '6141', '3910', '2110',
       '6150', '1703', '5380', '1755', '4910', '2310', '7021', '6836',
       '4340', '1540', '9920', '7973', '6031', '5555', '4820', '2223',
       '9667', '3440', '8647', '4218', '5001', '3720', '5620', '6000',
       '4051', '6986', '5575', '7520', '6110', '5640', '4052', '6042',
       '2381', '3930', '8433', '3118', '7712', '6250', '1430', '5031',
       '1851', '5530', '3270', '6630', '3051', '8851', '3350', '4780',
       '4453', '9308', '2470', '6761', '7300', '7040', '6980', '7534',
       '4130', '4577', '7972', '6032', '8890', '7780', '3060', '3920',
       '3512', '6890', '3391', '1670', '4524 JM', '7330', '3510', '7000',
       '2380', '5002', '6670', '2430', '7850', '8640', '8520', '4287',
       '3545', '2321', '1852', '2328', '3294', '6690', '6971', '7750',
       '6211', '5542', '7012', '3404', '6010', '2350', '9042', '1982',
       '9982', '2450', '1341', '3670', '8573', '5621', '2250', '7140',
       '5310', '7860', '7800', '3401', '6200', '4141', '6987', '8755',
       '7034', '3798', '2280', '5030', '3581', '6724', '7070', '6061',
       '3630', '7900', '7120', '6953', '1460', '2382', '6030', '8432',
       '7011', '2323', '7131', '2490', '6929', '7782', '7740', '7022',
       '7387', '5540', '7020', '5150', '2547', '2240', '4970', '7640',
       '4840', '5680', '1367', '4801', '6542', '6840', '3971', '3580',
       '3130', '4890', '5670', '9931', '7033', '2322', '1428', '6120',
       '3832', '4730', '3078', '2480', '6824', '6040', '3293', '8421',
       '4633', '7600', '3070', '3980', '3511', '2990', '3665', '2275',
       '3690', '9451', '3900', '6540', '3724', '3990', '6240', '3053',
       '3650', '3472', '2330', '3054', '4950', '7822', '4560', '3212',
       '3071', '3806', '2030', '4670', '3582', '5360', '3501', '3891',
       '5644', nan, '7730', '7181', '4700', '6851', '6717', '7880',
       '8554', '4845', '3018', '7321', '4672', '4987', '4990', '7810',
       '5651', '6750', '1457', '4850', '9180', '9403', '1130', '6637',
       '6687', '4860', '6741', '8587', '7322', '4852', '6782', '6972',
       '5351', '3730', '5032', '6440', '3640', '7180', '7190', '4470',
       '7350', '4623', '1741', '7332', '6560', '8552', '1315', '8953',
       '1404', '5523', '7866', '4452', '9551', '4217', '9881', '4877',
       '5501', '7030', '5650', '6680', '5300', '6640', '9921', '9932',
       '7533', '7742', '6927', '7331', '3381', '6140', '7711', '5646',
       '5140', '7870', '5570', '3211', '7863', '6238', '6674', '6534',
       '2288', '6921', '7130', '4219', '4210', '5022', '4537', '7618',
       '4608', '4980', '6970', '4837', '5630', '4367', '5024', '4861',
       '6530', '3621', '7041', '4770', '2242', '8954', '4607', '9406',
       '5370', '7804', '7382', '2387', '7610', '1360', '6567', '7063',
       '7942', '7522', '6223', '7370', '7943', '6781', '4458', '5600',
       '7134', '6460', '1474', '8904', '7031', '8978', '6500', '7506',
       '9988', '5561', '8431', '5350', '7050', '7536', '7061', '9961',
       '6020', '6221', '4506', '6044', '6182'], dtype=object)

In [189]:
df = df[df["postal_code"] != "4524 JM"]
df.postal_code.unique()

array(['1150', '1180', '1325', '4420', '8400', '9660', '3000', '1140',
       '1050', '1370', '1970', '8570', '2600', '1080', '2070', '2580',
       '1500', '9031', '2940', '9000', '8300', '6700', '4000', '4600',
       '9040', '9890', '9880', '4101', '9300', '9310', '2170', '2610',
       '9940', '1950', '4020', '2800', '6838', '4460', '9050', '4430',
       '1083', '1070', '9700', '8531', '9968', '1160', '9320', '8000',
       '6730', '1300', '1190', '3020', '2650', '9550', '2660', '9500',
       '9680', '8430', '4450', '2100', '1170', '1853', '9900', '9600',
       '9620', '2018', '2930', '1410', '1601', '8370', '2860', '1640',
       '1040', '2060', '9032', '3191', '2160', '9100', '1560', '2150',
       '8510', '1780', '4920', '2500', '2861', '2140', '9030', '8870',
       '1731', '3010', '9051', '2970', '8500', '9860', '4140', '3960',
       '4300', '2000', '9140', '3970', '9070', '8530', '4557', '8434',
       '9840', '1000', '8690', '1200', '4684', '2960', '2830', '8680',
       '9041', '2570', '4624', '9080', '8310', '1830', '8880', '3680',
       '8301', '9420', '9950', '1090', '2850', '1020', '2221', '7160',
       '1350', '8020', '9270', '3090', '6001', '6790', '6800', '3300',
       '9060', '8920', '9090', '8700', '8670', '1600', '9450', '9290',
       '3570', '1210', '9971', '2020', '2880', '9830', '8720', '8420',
       '1740', '1702', '1435', '8200', '1654', '2640', '3454', '8800',
       '3700', '9570', '3001', '1082', '4100', '4400', '4480', '4520',
       '6720', '7890', '3080', '8810', '1800', '3500', '8950', '2180',
       '9200', '3110', '4800', '2620', '7940', '1060', '1930', '1650',
       '2050', '1652', '9552', '9400', '6792', '9404', '8790', '9750',
       '6791', '4500', '2811', '3540', '9230', '2300', '2220', '9260',
       '4102', '7100', '9190', '8572', '9991', '2920', '9280', '6180',
       '9800', '4053', '8210', '9630', '1981', '9990', '2235', '3202',
       '1081', '1330', '8450', '9820', '3150', '1745', '4280', '9240',
       '8970', '1770', '4680', '3384', '2200', '9520', '4040', '8501',
       '9220', '1380', '9472', '1820', '1420', '6747', '3201', '3111',
       '7090', '8793', '1620', '8480', '2290', '5377', '1700', '5020',
       '9850', '2550', '1332', '8820', '2870', '5000', '1850', '8750',
       '5580', '1790', '1570', '1030', '9980', '3220', '3890', '1331',
       '8550', '8340', '4710', '9930', '8930', '6723', '3012', '8710',
       '2340', '1400', '2900', '3800', '1357', '9402', '9810', '3040',
       '1860', '4683', '1785', '3200', '4031', '4540', '4671', '8760',
       '5550', '5660', '9910', '1651', '4032', '9870', '9130', '8770',
       '6990', '3460', '2840', '6767', '8540', '9170', '7141', '2040',
       '7060', '1120', '5070', '9255', '3290', '9185', '1501', '7830',
       '9160', '3271', '9790', '8470', '6880', '1980', '2230', '3210',
       '9470', '1933', '3790', '2910', '2400', '6812', '8551', '8972',
       '9250', '7170', '6224', '6870', '8980', '1390', '1760', '4360',
       '4030', '4610', '4041', '9690', '6810', '2890', '1340', '9506',
       '8620', '6850', '3140', '1730', '2520', '3400', '4960', '6762',
       '5100', '9111', '4870', '2812', '6740', '6060', '3370', '6780',
       '3830', '1880', '3840', '5080', '5190', '2530', '3660', '9831',
       '6600', '6940', '6900', '2222', '7700', '1490', '2630', '1502',
       '8600', '1840', '3320', '6941', '3190', '3945', '3221', '9112',
       '6280', '1932', '7760', '4050', '2320', '9150', '9340', '4042',
       '4650', '6997', '1630', '8380', '6041', '2980', '2627', '4900',
       '4620', '2390', '9473', '8660', '3450', '4180', '4681', '8610',
       '3850', '4651', '4630', '1861', '6706', '2560', '8650', '8730',
       '5170', '4550', '5101', '3390', '1910', '4690', '1547', '4451',
       '2950', '4120', '4121', '8560', '7500', '4432', '6951', '8581',
       '4350', '1470', '5060', '8830', '3061', '8780', '1310', '4431',
       '8792', '4317', '6230', '1602', '4621', '4260', '4250', '5330',
       '6760', '3620', '8553', '9770', '2270', '1750', '2431', '4342',
       '1342', '9992', '4590', '8940', '7912', '2845', '1450', '8630',
       '2590', '4530', '5500', '3128', '3530', '3740', '9052', '7301',
       '3052', '8860', '3950', '3550', '3520', '4347', '8900', '9120',
       '8580', '2540', '6820', '6210', '2243', '7110', '4160', '4163',
       '2820', '3120', '7340', '6960', '1348', '9970', '3560', '4682',
       '1701', '2260', '8582', '8460', '4570', '9960', '2370', '5590',
       '3050', '1301', '8791', '8840', '3940', '6183', '6830', '8740',
       '1421', '3600', '9401', '2460', '6950', '6043', '6666', '7950',
       '6220', '8211', '8850', '5004', '5564', '1440', '4122', '7080',
       '8511', '5537', '3590', '2440', '6769', '1473', '1742', '3870',
       '3770', '6920', '7864', '2801', '7540', '6860', '5560', '6811',
       '1831', '1495', '1320', '8490', '1480', '1461', '7911', '3380',
       '4802', '1761', '1653', '7390', '4190', '2360', '5541', '8377',
       '3470', '3360', '7380', '3583', '6660', '6141', '3910', '2110',
       '6150', '1703', '5380', '1755', '4910', '2310', '7021', '6836',
       '4340', '1540', '9920', '7973', '6031', '5555', '4820', '2223',
       '9667', '3440', '8647', '4218', '5001', '3720', '5620', '6000',
       '4051', '6986', '5575', '7520', '6110', '5640', '4052', '6042',
       '2381', '3930', '8433', '3118', '7712', '6250', '1430', '5031',
       '1851', '5530', '3270', '6630', '3051', '8851', '3350', '4780',
       '4453', '9308', '2470', '6761', '7300', '7040', '6980', '7534',
       '4130', '4577', '7972', '6032', '8890', '7780', '3060', '3920',
       '3512', '6890', '3391', '1670', '7330', '3510', '7000', '2380',
       '5002', '6670', '2430', '7850', '8640', '8520', '4287', '3545',
       '2321', '1852', '2328', '3294', '6690', '6971', '7750', '6211',
       '5542', '7012', '3404', '6010', '2350', '9042', '1982', '9982',
       '2450', '1341', '3670', '8573', '5621', '2250', '7140', '5310',
       '7860', '7800', '3401', '6200', '4141', '6987', '8755', '7034',
       '3798', '2280', '5030', '3581', '6724', '7070', '6061', '3630',
       '7900', '7120', '6953', '1460', '2382', '6030', '8432', '7011',
       '2323', '7131', '2490', '6929', '7782', '7740', '7022', '7387',
       '5540', '7020', '5150', '2547', '2240', '4970', '7640', '4840',
       '5680', '1367', '4801', '6542', '6840', '3971', '3580', '3130',
       '4890', '5670', '9931', '7033', '2322', '1428', '6120', '3832',
       '4730', '3078', '2480', '6824', '6040', '3293', '8421', '4633',
       '7600', '3070', '3980', '3511', '2990', '3665', '2275', '3690',
       '9451', '3900', '6540', '3724', '3990', '6240', '3053', '3650',
       '3472', '2330', '3054', '4950', '7822', '4560', '3212', '3071',
       '3806', '2030', '4670', '3582', '5360', '3501', '3891', '5644',
       nan, '7730', '7181', '4700', '6851', '6717', '7880', '8554',
       '4845', '3018', '7321', '4672', '4987', '4990', '7810', '5651',
       '6750', '1457', '4850', '9180', '9403', '1130', '6637', '6687',
       '4860', '6741', '8587', '7322', '4852', '6782', '6972', '5351',
       '3730', '5032', '6440', '3640', '7180', '7190', '4470', '7350',
       '4623', '1741', '7332', '6560', '8552', '1315', '8953', '1404',
       '5523', '7866', '4452', '9551', '4217', '9881', '4877', '5501',
       '7030', '5650', '6680', '5300', '6640', '9921', '9932', '7533',
       '7742', '6927', '7331', '3381', '6140', '7711', '5646', '5140',
       '7870', '5570', '3211', '7863', '6238', '6674', '6534', '2288',
       '6921', '7130', '4219', '4210', '5022', '4537', '7618', '4608',
       '4980', '6970', '4837', '5630', '4367', '5024', '4861', '6530',
       '3621', '7041', '4770', '2242', '8954', '4607', '9406', '5370',
       '7804', '7382', '2387', '7610', '1360', '6567', '7063', '7942',
       '7522', '6223', '7370', '7943', '6781', '4458', '5600', '7134',
       '6460', '1474', '8904', '7031', '8978', '6500', '7506', '9988',
       '5561', '8431', '5350', '7050', '7536', '7061', '9961', '6020',
       '6221', '4506', '6044', '6182'], dtype=object)

In [190]:
row = df.iloc[5369]
print(row)

url                 https://www.immoweb.be/en/classified/duplex/fo...
bedrooms                                                          2.0
property_type                                               APARTMENT
property_subtype                                               DUPLEX
locality                                                   Aartselaar
postal_code                                                      2630
street                                               Della Faillelaan
number                                                             15
box                                                               NaN
kitchen                                                           0.0
facades                                                           2.0
price                                                        449000.0
furnished                                                         0.0
terrace                                                           1.0
terraceSurface                                                    NaN
fireplace                                                         0.0
fireplaceCount                                                    0.0
buildingState                                                    GOOD
garden                                                            0.0
gardenSurface                                                     0.0
pool                                                              0.0
landSurface                                                       NaN
livingArea                                                      161.0
surfaceOfThePlot                                                  NaN
typeOfSale                                                        NaN
energy_rating                                                     NaN
Name: 6023, dtype: object

In [191]:
df.postal_code.describe()

count     16305
unique      907
top        8300
freq        886
Name: postal_code, dtype: object

In [198]:
df.postal_code.astype(float)

house_index
0        1150.0
1        1180.0
2        1325.0
3        4420.0
4        8400.0
          ...
19973    2230.0
19974    8800.0
19975    8020.0
19976    8870.0
19977    1950.0
Name: postal_code, Length: 16306, dtype: float64

In [197]:
df.postal_code.info()

<class 'pandas.core.series.Series'>
Index: 16306 entries, 0 to 19977
Series name: postal_code
Non-Null Count  Dtype
--------------  -----
16305 non-null  object
dtypes: object(1)
memory usage: 254.8+ KB

In [203]:
df[df["postal_code"] == np.nan].value_counts

<bound method DataFrame.value_counts of Empty DataFrame
Columns: [url, bedrooms, property_type, property_subtype, locality, postal_code, street, number, box, kitchen, facades, price, furnished, terrace, terraceSurface, fireplace, fireplaceCount, buildingState, garden, gardenSurface, pool, landSurface, livingArea, surfaceOfThePlot, typeOfSale, energy_rating]
Index: []

[0 rows x 26 columns]>

In [205]:
df["postal_code"] = pd.to_numeric(df["postal_code"], errors="coerce")

In [207]:
df.postal_code.unique()

array([1150., 1180., 1325., 4420., 8400., 9660., 3000., 1140., 1050.,
       1370., 1970., 8570., 2600., 1080., 2070., 2580., 1500., 9031.,
       2940., 9000., 8300., 6700., 4000., 4600., 9040., 9890., 9880.,
       4101., 9300., 9310., 2170., 2610., 9940., 1950., 4020., 2800.,
       6838., 4460., 9050., 4430., 1083., 1070., 9700., 8531., 9968.,
       1160., 9320., 8000., 6730., 1300., 1190., 3020., 2650., 9550.,
       2660., 9500., 9680., 8430., 4450., 2100., 1170., 1853., 9900.,
       9600., 9620., 2018., 2930., 1410., 1601., 8370., 2860., 1640.,
       1040., 2060., 9032., 3191., 2160., 9100., 1560., 2150., 8510.,
       1780., 4920., 2500., 2861., 2140., 9030., 8870., 1731., 3010.,
       9051., 2970., 8500., 9860., 4140., 3960., 4300., 2000., 9140.,
       3970., 9070., 8530., 4557., 8434., 9840., 1000., 8690., 1200.,
       4684., 2960., 2830., 8680., 9041., 2570., 4624., 9080., 8310.,
       1830., 8880., 3680., 8301., 9420., 9950., 1090., 2850., 1020.,
       2221., 7160., 1350., 8020., 9270., 3090., 6001., 6790., 6800.,
       3300., 9060., 8920., 9090., 8700., 8670., 1600., 9450., 9290.,
       3570., 1210., 9971., 2020., 2880., 9830., 8720., 8420., 1740.,
       1702., 1435., 8200., 1654., 2640., 3454., 8800., 3700., 9570.,
       3001., 1082., 4100., 4400., 4480., 4520., 6720., 7890., 3080.,
       8810., 1800., 3500., 8950., 2180., 9200., 3110., 4800., 2620.,
       7940., 1060., 1930., 1650., 2050., 1652., 9552., 9400., 6792.,
       9404., 8790., 9750., 6791., 4500., 2811., 3540., 9230., 2300.,
       2220., 9260., 4102., 7100., 9190., 8572., 9991., 2920., 9280.,
       6180., 9800., 4053., 8210., 9630., 1981., 9990., 2235., 3202.,
       1081., 1330., 8450., 9820., 3150., 1745., 4280., 9240., 8970.,
       1770., 4680., 3384., 2200., 9520., 4040., 8501., 9220., 1380.,
       9472., 1820., 1420., 6747., 3201., 3111., 7090., 8793., 1620.,
       8480., 2290., 5377., 1700., 5020., 9850., 2550., 1332., 8820.,
       2870., 5000., 1850., 8750., 5580., 1790., 1570., 1030., 9980.,
       3220., 3890., 1331., 8550., 8340., 4710., 9930., 8930., 6723.,
       3012., 8710., 2340., 1400., 2900., 3800., 1357., 9402., 9810.,
       3040., 1860., 4683., 1785., 3200., 4031., 4540., 4671., 8760.,
       5550., 5660., 9910., 1651., 4032., 9870., 9130., 8770., 6990.,
       3460., 2840., 6767., 8540., 9170., 7141., 2040., 7060., 1120.,
       5070., 9255., 3290., 9185., 1501., 7830., 9160., 3271., 9790.,
       8470., 6880., 1980., 2230., 3210., 9470., 1933., 3790., 2910.,
       2400., 6812., 8551., 8972., 9250., 7170., 6224., 6870., 8980.,
       1390., 1760., 4360., 4030., 4610., 4041., 9690., 6810., 2890.,
       1340., 9506., 8620., 6850., 3140., 1730., 2520., 3400., 4960.,
       6762., 5100., 9111., 4870., 2812., 6740., 6060., 3370., 6780.,
       3830., 1880., 3840., 5080., 5190., 2530., 3660., 9831., 6600.,
       6940., 6900., 2222., 7700., 1490., 2630., 1502., 8600., 1840.,
       3320., 6941., 3190., 3945., 3221., 9112., 6280., 1932., 7760.,
       4050., 2320., 9150., 9340., 4042., 4650., 6997., 1630., 8380.,
       6041., 2980., 2627., 4900., 4620., 2390., 9473., 8660., 3450.,
       4180., 4681., 8610., 3850., 4651., 4630., 1861., 6706., 2560.,
       8650., 8730., 5170., 4550., 5101., 3390., 1910., 4690., 1547.,
       4451., 2950., 4120., 4121., 8560., 7500., 4432., 6951., 8581.,
       4350., 1470., 5060., 8830., 3061., 8780., 1310., 4431., 8792.,
       4317., 6230., 1602., 4621., 4260., 4250., 5330., 6760., 3620.,
       8553., 9770., 2270., 1750., 2431., 4342., 1342., 9992., 4590.,
       8940., 7912., 2845., 1450., 8630., 2590., 4530., 5500., 3128.,
       3530., 3740., 9052., 7301., 3052., 8860., 3950., 3550., 3520.,
       4347., 8900., 9120., 8580., 2540., 6820., 6210., 2243., 7110.,
       4160., 4163., 2820., 3120., 7340., 6960., 1348., 9970., 3560.,
       4682., 1701., 2260., 8582., 8460., 4570., 9960., 2370., 5590.,
       3050., 1301., 8791., 8840., 3940., 6183., 6830., 8740., 1421.,
       3600., 9401., 2460., 6950., 6043., 6666., 7950., 6220., 8211.,
       8850., 5004., 5564., 1440., 4122., 7080., 8511., 5537., 3590.,
       2440., 6769., 1473., 1742., 3870., 3770., 6920., 7864., 2801.,
       7540., 6860., 5560., 6811., 1831., 1495., 1320., 8490., 1480.,
       1461., 7911., 3380., 4802., 1761., 1653., 7390., 4190., 2360.,
       5541., 8377., 3470., 3360., 7380., 3583., 6660., 6141., 3910.,
       2110., 6150., 1703., 5380., 1755., 4910., 2310., 7021., 6836.,
       4340., 1540., 9920., 7973., 6031., 5555., 4820., 2223., 9667.,
       3440., 8647., 4218., 5001., 3720., 5620., 6000., 4051., 6986.,
       5575., 7520., 6110., 5640., 4052., 6042., 2381., 3930., 8433.,
       3118., 7712., 6250., 1430., 5031., 1851., 5530., 3270., 6630.,
       3051., 8851., 3350., 4780., 4453., 9308., 2470., 6761., 7300.,
       7040., 6980., 7534., 4130., 4577., 7972., 6032., 8890., 7780.,
       3060., 3920., 3512., 6890., 3391., 1670., 7330., 3510., 7000.,
       2380., 5002., 6670., 2430., 7850., 8640., 8520., 4287., 3545.,
       2321., 1852., 2328., 3294., 6690., 6971., 7750., 6211., 5542.,
       7012., 3404., 6010., 2350., 9042., 1982., 9982., 2450., 1341.,
       3670., 8573., 5621., 2250., 7140., 5310., 7860., 7800., 3401.,
       6200., 4141., 6987., 8755., 7034., 3798., 2280., 5030., 3581.,
       6724., 7070., 6061., 3630., 7900., 7120., 6953., 1460., 2382.,
       6030., 8432., 7011., 2323., 7131., 2490., 6929., 7782., 7740.,
       7022., 7387., 5540., 7020., 5150., 2547., 2240., 4970., 7640.,
       4840., 5680., 1367., 4801., 6542., 6840., 3971., 3580., 3130.,
       4890., 5670., 9931., 7033., 2322., 1428., 6120., 3832., 4730.,
       3078., 2480., 6824., 6040., 3293., 8421., 4633., 7600., 3070.,
       3980., 3511., 2990., 3665., 2275., 3690., 9451., 3900., 6540.,
       3724., 3990., 6240., 3053., 3650., 3472., 2330., 3054., 4950.,
       7822., 4560., 3212., 3071., 3806., 2030., 4670., 3582., 5360.,
       3501., 3891., 5644.,   nan, 7730., 7181., 4700., 6851., 6717.,
       7880., 8554., 4845., 3018., 7321., 4672., 4987., 4990., 7810.,
       5651., 6750., 1457., 4850., 9180., 9403., 1130., 6637., 6687.,
       4860., 6741., 8587., 7322., 4852., 6782., 6972., 5351., 3730.,
       5032., 6440., 3640., 7180., 7190., 4470., 7350., 4623., 1741.,
       7332., 6560., 8552., 1315., 8953., 1404., 5523., 7866., 4452.,
       9551., 4217., 9881., 4877., 5501., 7030., 5650., 6680., 5300.,
       6640., 9921., 9932., 7533., 7742., 6927., 7331., 3381., 6140.,
       7711., 5646., 5140., 7870., 5570., 3211., 7863., 6238., 6674.,
       6534., 2288., 6921., 7130., 4219., 4210., 5022., 4537., 7618.,
       4608., 4980., 6970., 4837., 5630., 4367., 5024., 4861., 6530.,
       3621., 7041., 4770., 2242., 8954., 4607., 9406., 5370., 7804.,
       7382., 2387., 7610., 1360., 6567., 7063., 7942., 7522., 6223.,
       7370., 7943., 6781., 4458., 5600., 7134., 6460., 1474., 8904.,
       7031., 8978., 6500., 7506., 9988., 5561., 8431., 5350., 7050.,
       7536., 7061., 9961., 6020., 6221., 4506., 6044., 6182.])

In [208]:
# drop NAN values in column
df = df.dropna(subset=["postal_code"])

In [209]:
df.postal_code.unique()

array([1150., 1180., 1325., 4420., 8400., 9660., 3000., 1140., 1050.,
       1370., 1970., 8570., 2600., 1080., 2070., 2580., 1500., 9031.,
       2940., 9000., 8300., 6700., 4000., 4600., 9040., 9890., 9880.,
       4101., 9300., 9310., 2170., 2610., 9940., 1950., 4020., 2800.,
       6838., 4460., 9050., 4430., 1083., 1070., 9700., 8531., 9968.,
       1160., 9320., 8000., 6730., 1300., 1190., 3020., 2650., 9550.,
       2660., 9500., 9680., 8430., 4450., 2100., 1170., 1853., 9900.,
       9600., 9620., 2018., 2930., 1410., 1601., 8370., 2860., 1640.,
       1040., 2060., 9032., 3191., 2160., 9100., 1560., 2150., 8510.,
       1780., 4920., 2500., 2861., 2140., 9030., 8870., 1731., 3010.,
       9051., 2970., 8500., 9860., 4140., 3960., 4300., 2000., 9140.,
       3970., 9070., 8530., 4557., 8434., 9840., 1000., 8690., 1200.,
       4684., 2960., 2830., 8680., 9041., 2570., 4624., 9080., 8310.,
       1830., 8880., 3680., 8301., 9420., 9950., 1090., 2850., 1020.,
       2221., 7160., 1350., 8020., 9270., 3090., 6001., 6790., 6800.,
       3300., 9060., 8920., 9090., 8700., 8670., 1600., 9450., 9290.,
       3570., 1210., 9971., 2020., 2880., 9830., 8720., 8420., 1740.,
       1702., 1435., 8200., 1654., 2640., 3454., 8800., 3700., 9570.,
       3001., 1082., 4100., 4400., 4480., 4520., 6720., 7890., 3080.,
       8810., 1800., 3500., 8950., 2180., 9200., 3110., 4800., 2620.,
       7940., 1060., 1930., 1650., 2050., 1652., 9552., 9400., 6792.,
       9404., 8790., 9750., 6791., 4500., 2811., 3540., 9230., 2300.,
       2220., 9260., 4102., 7100., 9190., 8572., 9991., 2920., 9280.,
       6180., 9800., 4053., 8210., 9630., 1981., 9990., 2235., 3202.,
       1081., 1330., 8450., 9820., 3150., 1745., 4280., 9240., 8970.,
       1770., 4680., 3384., 2200., 9520., 4040., 8501., 9220., 1380.,
       9472., 1820., 1420., 6747., 3201., 3111., 7090., 8793., 1620.,
       8480., 2290., 5377., 1700., 5020., 9850., 2550., 1332., 8820.,
       2870., 5000., 1850., 8750., 5580., 1790., 1570., 1030., 9980.,
       3220., 3890., 1331., 8550., 8340., 4710., 9930., 8930., 6723.,
       3012., 8710., 2340., 1400., 2900., 3800., 1357., 9402., 9810.,
       3040., 1860., 4683., 1785., 3200., 4031., 4540., 4671., 8760.,
       5550., 5660., 9910., 1651., 4032., 9870., 9130., 8770., 6990.,
       3460., 2840., 6767., 8540., 9170., 7141., 2040., 7060., 1120.,
       5070., 9255., 3290., 9185., 1501., 7830., 9160., 3271., 9790.,
       8470., 6880., 1980., 2230., 3210., 9470., 1933., 3790., 2910.,
       2400., 6812., 8551., 8972., 9250., 7170., 6224., 6870., 8980.,
       1390., 1760., 4360., 4030., 4610., 4041., 9690., 6810., 2890.,
       1340., 9506., 8620., 6850., 3140., 1730., 2520., 3400., 4960.,
       6762., 5100., 9111., 4870., 2812., 6740., 6060., 3370., 6780.,
       3830., 1880., 3840., 5080., 5190., 2530., 3660., 9831., 6600.,
       6940., 6900., 2222., 7700., 1490., 2630., 1502., 8600., 1840.,
       3320., 6941., 3190., 3945., 3221., 9112., 6280., 1932., 7760.,
       4050., 2320., 9150., 9340., 4042., 4650., 6997., 1630., 8380.,
       6041., 2980., 2627., 4900., 4620., 2390., 9473., 8660., 3450.,
       4180., 4681., 8610., 3850., 4651., 4630., 1861., 6706., 2560.,
       8650., 8730., 5170., 4550., 5101., 3390., 1910., 4690., 1547.,
       4451., 2950., 4120., 4121., 8560., 7500., 4432., 6951., 8581.,
       4350., 1470., 5060., 8830., 3061., 8780., 1310., 4431., 8792.,
       4317., 6230., 1602., 4621., 4260., 4250., 5330., 6760., 3620.,
       8553., 9770., 2270., 1750., 2431., 4342., 1342., 9992., 4590.,
       8940., 7912., 2845., 1450., 8630., 2590., 4530., 5500., 3128.,
       3530., 3740., 9052., 7301., 3052., 8860., 3950., 3550., 3520.,
       4347., 8900., 9120., 8580., 2540., 6820., 6210., 2243., 7110.,
       4160., 4163., 2820., 3120., 7340., 6960., 1348., 9970., 3560.,
       4682., 1701., 2260., 8582., 8460., 4570., 9960., 2370., 5590.,
       3050., 1301., 8791., 8840., 3940., 6183., 6830., 8740., 1421.,
       3600., 9401., 2460., 6950., 6043., 6666., 7950., 6220., 8211.,
       8850., 5004., 5564., 1440., 4122., 7080., 8511., 5537., 3590.,
       2440., 6769., 1473., 1742., 3870., 3770., 6920., 7864., 2801.,
       7540., 6860., 5560., 6811., 1831., 1495., 1320., 8490., 1480.,
       1461., 7911., 3380., 4802., 1761., 1653., 7390., 4190., 2360.,
       5541., 8377., 3470., 3360., 7380., 3583., 6660., 6141., 3910.,
       2110., 6150., 1703., 5380., 1755., 4910., 2310., 7021., 6836.,
       4340., 1540., 9920., 7973., 6031., 5555., 4820., 2223., 9667.,
       3440., 8647., 4218., 5001., 3720., 5620., 6000., 4051., 6986.,
       5575., 7520., 6110., 5640., 4052., 6042., 2381., 3930., 8433.,
       3118., 7712., 6250., 1430., 5031., 1851., 5530., 3270., 6630.,
       3051., 8851., 3350., 4780., 4453., 9308., 2470., 6761., 7300.,
       7040., 6980., 7534., 4130., 4577., 7972., 6032., 8890., 7780.,
       3060., 3920., 3512., 6890., 3391., 1670., 7330., 3510., 7000.,
       2380., 5002., 6670., 2430., 7850., 8640., 8520., 4287., 3545.,
       2321., 1852., 2328., 3294., 6690., 6971., 7750., 6211., 5542.,
       7012., 3404., 6010., 2350., 9042., 1982., 9982., 2450., 1341.,
       3670., 8573., 5621., 2250., 7140., 5310., 7860., 7800., 3401.,
       6200., 4141., 6987., 8755., 7034., 3798., 2280., 5030., 3581.,
       6724., 7070., 6061., 3630., 7900., 7120., 6953., 1460., 2382.,
       6030., 8432., 7011., 2323., 7131., 2490., 6929., 7782., 7740.,
       7022., 7387., 5540., 7020., 5150., 2547., 2240., 4970., 7640.,
       4840., 5680., 1367., 4801., 6542., 6840., 3971., 3580., 3130.,
       4890., 5670., 9931., 7033., 2322., 1428., 6120., 3832., 4730.,
       3078., 2480., 6824., 6040., 3293., 8421., 4633., 7600., 3070.,
       3980., 3511., 2990., 3665., 2275., 3690., 9451., 3900., 6540.,
       3724., 3990., 6240., 3053., 3650., 3472., 2330., 3054., 4950.,
       7822., 4560., 3212., 3071., 3806., 2030., 4670., 3582., 5360.,
       3501., 3891., 5644., 7730., 7181., 4700., 6851., 6717., 7880.,
       8554., 4845., 3018., 7321., 4672., 4987., 4990., 7810., 5651.,
       6750., 1457., 4850., 9180., 9403., 1130., 6637., 6687., 4860.,
       6741., 8587., 7322., 4852., 6782., 6972., 5351., 3730., 5032.,
       6440., 3640., 7180., 7190., 4470., 7350., 4623., 1741., 7332.,
       6560., 8552., 1315., 8953., 1404., 5523., 7866., 4452., 9551.,
       4217., 9881., 4877., 5501., 7030., 5650., 6680., 5300., 6640.,
       9921., 9932., 7533., 7742., 6927., 7331., 3381., 6140., 7711.,
       5646., 5140., 7870., 5570., 3211., 7863., 6238., 6674., 6534.,
       2288., 6921., 7130., 4219., 4210., 5022., 4537., 7618., 4608.,
       4980., 6970., 4837., 5630., 4367., 5024., 4861., 6530., 3621.,
       7041., 4770., 2242., 8954., 4607., 9406., 5370., 7804., 7382.,
       2387., 7610., 1360., 6567., 7063., 7942., 7522., 6223., 7370.,
       7943., 6781., 4458., 5600., 7134., 6460., 1474., 8904., 7031.,
       8978., 6500., 7506., 9988., 5561., 8431., 5350., 7050., 7536.,
       7061., 9961., 6020., 6221., 4506., 6044., 6182.])

In [211]:
def map_postal_code_to_province(postal_code):
    if 1000 <= postal_code <= 1299:
        return "brussels_capital"
    elif 1300 <= postal_code <= 1499:
        return "walloon_brabant"
    elif 1500 <= postal_code <= 1999:
        return "flemish_brabant"
    elif 3000 <= postal_code <= 3499:
        return "flemish_brabant_extended"
    elif 2000 <= postal_code <= 2999:
        return "antwerp_province"
    elif 3500 <= postal_code <= 3999:
        return "limburg_province"
    elif 4000 <= postal_code <= 4999:
        return "liÃ¨ge_province"
    elif 5000 <= postal_code <= 5999:
        return "namur_province"
    elif 6000 <= postal_code <= 6599:
        return "hainaut_province"
    elif 7000 <= postal_code <= 7999:
        return "hainaut_extended"
    elif 6600 <= postal_code <= 6999:
        return "luxembourg_province"
    elif 8000 <= postal_code <= 8999:
        return "west_flanders"
    elif 9000 <= postal_code <= 9999:
        return "east_flanders"
    else:
        return np.nan

df["province"] = df["postal_code"].apply(map_postal_code_to_province)

In [212]:
df.postal_code.info()

<class 'pandas.core.series.Series'>
Index: 16305 entries, 0 to 19977
Series name: postal_code
Non-Null Count  Dtype
--------------  -----
16305 non-null  float64
dtypes: float64(1)
memory usage: 254.8 KB

In [281]:
df.province.head(10)

house_index
0            brussels_capital
1            brussels_capital
2             walloon_brabant
3              liÃ¨ge_province
4               west_flanders
5               east_flanders
6    flemish_brabant_extended
7            brussels_capital
8            brussels_capital
9             walloon_brabant
Name: province, dtype: object

In [217]:
df.head(20)

,url,bedrooms,property_type,property_subtype,locality,postal_code,street,number,box,kitchen,...,buildingState,garden,gardenSurface,pool,landSurface,livingArea,surfaceOfThePlot,typeOfSale,energy_rating,province
house_index,,,,,,,,,,,,,,,,,,,,,
0,https://www.immoweb.be/en/classified/house/for...,4.0,HOUSE,HOUSE,Woluwe-Saint-Pierre,1150.0,Rue au Bois,85,NaN,1.0,...,TO_RENOVATE,1.0,170.0,0.0,270.0,180.0,270.0,NaN,NaN,brussels_capital
1,https://www.immoweb.be/en/classified/apartment...,3.0,HOUSE,APARTMENT_BLOCK,Uccle,1180.0,Rue de Verrewinkel,38,NaN,1.0,...,TO_RENOVATE,1.0,100.0,0.0,177.0,195.0,177.0,NaN,NaN,brussels_capital
2,https://www.immoweb.be/en/classified/villa/for...,10.0,HOUSE,VILLA,Corroy-le-Grand,1325.0,Rue du Warichet,12,NaN,1.0,...,AS_NEW,1.0,3752.0,0.0,3985.0,510.0,3985.0,NaN,NaN,walloon_brabant
3,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Saint-Nicolas,4420.0,Rue Voie des Vaux,262,NaN,1.0,...,AS_NEW,1.0,492.0,0.0,600.0,141.0,600.0,NaN,NaN,liÃ¨ge_province
4,https://www.immoweb.be/en/classified/apartment...,3.0,APARTMENT,APARTMENT,Oostende,8400.0,Torhoutsesteenweg,278,301,1.0,...,GOOD,0.0,0.0,0.0,NaN,132.0,NaN,NaN,NaN,west_flanders
5,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Brakel,9660.0,Kunnenbergstraat,13,NaN,0.0,...,TO_RENOVATE,0.0,0.0,0.0,737.0,147.0,737.0,NaN,NaN,east_flanders
6,https://www.immoweb.be/en/classified/apartment...,6.0,HOUSE,APARTMENT_BLOCK,Leuven,3000.0,JB Van Monsstraat,43,NaN,0.0,...,GOOD,0.0,0.0,0.0,106.0,167.0,106.0,NaN,NaN,flemish_brabant_extended
7,https://www.immoweb.be/en/classified/apartment...,3.0,APARTMENT,APARTMENT,Evere,1140.0,AllÃ©es du Languedoc,2,NaN,1.0,...,TO_RENOVATE,0.0,0.0,0.0,NaN,116.0,NaN,NaN,NaN,brussels_capital
8,https://www.immoweb.be/en/classified/apartment...,3.0,APARTMENT,APARTMENT,Ixelles,1050.0,Place Marie-JosÃ©,6,NaN,1.0,...,GOOD,0.0,0.0,0.0,NaN,140.0,NaN,NaN,NaN,brussels_capital
9,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,JODOIGNE,1370.0,Elst,60,NaN,1.0,...,TO_RENOVATE,1.0,2575.0,0.0,2575.0,150.0,2575.0,NaN,NaN,walloon_brabant
10,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Wezembeek-Oppem,1970.0,Avenue des Cygnes Sauvages,2,NaN,1.0,...,TO_RENOVATE,1.0,200.0,0.0,571.0,155.0,571.0,NaN,NaN,flemish_brabant
11,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Anzegem,8570.0,Zijptestraat,4,NaN,1.0,...,GOOD,1.0,270.0,0.0,497.0,175.0,497.0,NaN,NaN,west_flanders
12,https://www.immoweb.be/en/classified/apartment...,2.0,APARTMENT,APARTMENT,BERCHEM,2600.0,Lode Vissenaekenstraat,2,1v,1.0,...,AS_NEW,0.0,0.0,0.0,NaN,85.0,NaN,NaN,NaN,antwerp_province
13,https://www.immoweb.be/en/classified/apartment...,1.0,APARTMENT,APARTMENT,SINT-JANS-MOLENBEEK,1080.0,Rue Michel Zwaab,12,NaN,0.0,...,GOOD,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,brussels_capital
14,https://www.immoweb.be/en/classified/apartment...,1.0,APARTMENT,APARTMENT,Burcht,2070.0,Dorpstraat,70,1,0.0,...,JUST_RENOVATED,0.0,0.0,0.0,NaN,92.0,NaN,NaN,NaN,antwerp_province
15,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Putte,2580.0,Eksterstraat,2D,NaN,1.0,...,TO_RENOVATE,0.0,0.0,0.0,454.0,212.0,454.0,NaN,NaN,antwerp_province
16,https://www.immoweb.be/en/classified/apartment...,3.0,APARTMENT,APARTMENT,Uccle,1180.0,Avenue Coghen,278,NaN,1.0,...,TO_BE_DONE_UP,0.0,0.0,0.0,NaN,139.0,NaN,NaN,NaN,brussels_capital
17,https://www.immoweb.be/en/classified/apartment...,4.0,APARTMENT,APARTMENT,HALLE,1500.0,Prinses Paolalaan,8,NaN,1.0,...,JUST_RENOVATED,0.0,0.0,0.0,NaN,201.0,NaN,NaN,NaN,flemish_brabant
18,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Gent Drongen,9031.0,Noordhoutstraat,19,NaN,1.0,...,TO_BE_DONE_UP,0.0,0.0,0.0,5018.0,408.0,5018.0,NaN,NaN,east_flanders
19,https://www.immoweb.be/en/classified/apartment...,2.0,APARTMENT,APARTMENT,Stabroek,2940.0,Kleine Molenweg,58,V2,1.0,...,JUST_RENOVATED,0.0,0.0,0.0,NaN,80.0,NaN,NaN,NaN,antwerp_province

In [220]:
df = df.drop(columns=["energy_rating"])

In [221]:
df.head(15)

,url,bedrooms,property_type,property_subtype,locality,postal_code,street,number,box,kitchen,...,fireplaceCount,buildingState,garden,gardenSurface,pool,landSurface,livingArea,surfaceOfThePlot,typeOfSale,province
house_index,,,,,,,,,,,,,,,,,,,,,
0,https://www.immoweb.be/en/classified/house/for...,4.0,HOUSE,HOUSE,Woluwe-Saint-Pierre,1150.0,Rue au Bois,85,NaN,1.0,...,0.0,TO_RENOVATE,1.0,170.0,0.0,270.0,180.0,270.0,NaN,brussels_capital
1,https://www.immoweb.be/en/classified/apartment...,3.0,HOUSE,APARTMENT_BLOCK,Uccle,1180.0,Rue de Verrewinkel,38,NaN,1.0,...,0.0,TO_RENOVATE,1.0,100.0,0.0,177.0,195.0,177.0,NaN,brussels_capital
2,https://www.immoweb.be/en/classified/villa/for...,10.0,HOUSE,VILLA,Corroy-le-Grand,1325.0,Rue du Warichet,12,NaN,1.0,...,0.0,AS_NEW,1.0,3752.0,0.0,3985.0,510.0,3985.0,NaN,walloon_brabant
3,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Saint-Nicolas,4420.0,Rue Voie des Vaux,262,NaN,1.0,...,0.0,AS_NEW,1.0,492.0,0.0,600.0,141.0,600.0,NaN,liÃ¨ge_province
4,https://www.immoweb.be/en/classified/apartment...,3.0,APARTMENT,APARTMENT,Oostende,8400.0,Torhoutsesteenweg,278,301,1.0,...,0.0,GOOD,0.0,0.0,0.0,NaN,132.0,NaN,NaN,west_flanders
5,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Brakel,9660.0,Kunnenbergstraat,13,NaN,0.0,...,0.0,TO_RENOVATE,0.0,0.0,0.0,737.0,147.0,737.0,NaN,east_flanders
6,https://www.immoweb.be/en/classified/apartment...,6.0,HOUSE,APARTMENT_BLOCK,Leuven,3000.0,JB Van Monsstraat,43,NaN,0.0,...,0.0,GOOD,0.0,0.0,0.0,106.0,167.0,106.0,NaN,flemish_brabant_extended
7,https://www.immoweb.be/en/classified/apartment...,3.0,APARTMENT,APARTMENT,Evere,1140.0,AllÃ©es du Languedoc,2,NaN,1.0,...,0.0,TO_RENOVATE,0.0,0.0,0.0,NaN,116.0,NaN,NaN,brussels_capital
8,https://www.immoweb.be/en/classified/apartment...,3.0,APARTMENT,APARTMENT,Ixelles,1050.0,Place Marie-JosÃ©,6,NaN,1.0,...,0.0,GOOD,0.0,0.0,0.0,NaN,140.0,NaN,NaN,brussels_capital
9,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,JODOIGNE,1370.0,Elst,60,NaN,1.0,...,0.0,TO_RENOVATE,1.0,2575.0,0.0,2575.0,150.0,2575.0,NaN,walloon_brabant
10,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Wezembeek-Oppem,1970.0,Avenue des Cygnes Sauvages,2,NaN,1.0,...,0.0,TO_RENOVATE,1.0,200.0,0.0,571.0,155.0,571.0,NaN,flemish_brabant
11,https://www.immoweb.be/en/classified/house/for...,3.0,HOUSE,HOUSE,Anzegem,8570.0,Zijptestraat,4,NaN,1.0,...,0.0,GOOD,1.0,270.0,0.0,497.0,175.0,497.0,NaN,west_flanders
12,https://www.immoweb.be/en/classified/apartment...,2.0,APARTMENT,APARTMENT,BERCHEM,2600.0,Lode Vissenaekenstraat,2,1v,1.0,...,0.0,AS_NEW,0.0,0.0,0.0,NaN,85.0,NaN,NaN,antwerp_province
13,https://www.immoweb.be/en/classified/apartment...,1.0,APARTMENT,APARTMENT,SINT-JANS-MOLENBEEK,1080.0,Rue Michel Zwaab,12,NaN,0.0,...,0.0,GOOD,0.0,0.0,0.0,NaN,NaN,NaN,NaN,brussels_capital
14,https://www.immoweb.be/en/classified/apartment...,1.0,APARTMENT,APARTMENT,Burcht,2070.0,Dorpstraat,70,1,0.0,...,0.0,JUST_RENOVATED,0.0,0.0,0.0,NaN,92.0,NaN,NaN,antwerp_province

In [226]:
df.columns

Index(['url', 'bedrooms', 'property_type', 'property_subtype', 'locality',
       'postal_code', 'street', 'number', 'box', 'kitchen', 'facades', 'price',
       'furnished', 'terrace', 'terraceSurface', 'fireplace', 'fireplaceCount',
       'buildingState', 'garden', 'gardenSurface', 'pool', 'landSurface',
       'livingArea', 'surfaceOfThePlot', 'typeOfSale', 'province'],
      dtype='object')

In [287]:
group_per_province = df.groupby("province")["price"]

In [247]:
per_province = df.sort_values(["province", "price"], ascending=[True, False])

In [290]:
group_per_province.head().max()

1935000.0

In [260]:
df = df.replace(["", None], np.nan)

In [261]:
df = df.replace("", np.nan)

In [262]:
df = df.map(lambda x: np.nan if x == "" else x)

In [264]:
nan_values = df.isna()
nan_values

,url,bedrooms,property_type,property_subtype,locality,postal_code,street,number,box,kitchen,...,fireplaceCount,buildingState,garden,gardenSurface,pool,landSurface,livingArea,surfaceOfThePlot,typeOfSale,province
house_index,,,,,,,,,,,,,,,,,,,,,
0,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19973,False,False,False,False,False,False,False,False,True,False,...,False,True,False,False,False,False,True,False,False,False
19974,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False
19975,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False
19976,False,False,False,False,False,False,False,False,True,False,...,False,True,False,False,False,False,True,False,True,False
19977,False,False,False,False,False,False,False,False,True,False,...,False,True,False,False,False,False,True,False,False,False

In [266]:
nan_count = df.isna().sum().sum()
nan_count

52535

In [272]:
df = df.replace(r'^\s*$', np.nan, regex=True)
df = df.map(lambda x: np.nan if isinstance(x, str) and x.strip() == "" else x)

In [274]:
columns_with_nan = df.isna().any()
print(columns_with_nan)

url                 False
bedrooms            False
property_type       False
property_subtype    False
locality            False
postal_code         False
street               True
number               True
box                  True
kitchen             False
facades              True
price                True
furnished           False
terrace             False
terraceSurface       True
fireplace           False
fireplaceCount      False
buildingState        True
garden              False
gardenSurface       False
pool                False
landSurface          True
livingArea           True
surfaceOfThePlot     True
typeOfSale           True
province            False
dtype: bool

In [276]:
df.box.iloc[0]

nan

AttributeError: 'float' object has no attribute 'index'

In [292]:
df["price"].iloc[10500000]

IndexError: single positional indexer is out-of-bounds

In [275]:
df.to_csv("properties_data_set_19_11_20H00.csv", index = True)
print("DataFrame saved to 'properties_data_set_19_11_20H00'")

DataFrame saved to 'properties_data_set_19_11_20H00'

In [ ]:

import time
from threading import Thread
from time import perf_counter
import requests
from bs4 import BeautifulSoup
import json
import csv
from typing import Any
from concurrent.futures import ThreadPoolExecutor, as_completed
import os
import pandas as pd


def fetch_links(url,page,property_links):

    url=f"{url}&page={page}"
    start_time = perf_counter()
    response = requests.get(url, headers={"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"})
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, 'html.parser')
        for res in soup.select('article.card.card--result div.card--result__body a.card__title-link'):
            property_links.append(res.attrs["href"])
        duration = perf_counter() - start_time
        print(f"Page {page} fetched in {duration:.4f} seconds.")
    else:
        print(f"Error on page {page}")
    
def fetch_multiple_pages(base_url, start_page, end_page,property_links):
    # Create a list of page numbers to iterate over
    pages = list(range(start_page, end_page))
    
    # Use ThreadPoolExecutor to fetch all pages concurrently
    with ThreadPoolExecutor(max_workers=8) as executor:  # Adjust max_workers based on your needs
        # Submit tasks to fetch data for each page from the base URL
        executor.map(lambda page_number: fetch_links(base_url, page_number,property_links), pages)
    

def write_links_csv(file_path,property_links):
    print("In write csv")
    with open(file_path, 'w') as csvfile:
        writer = csv.writer(csvfile)
        for url in property_links:
            writer.writerow([url])


def get_in(data: dict, keys: list, default: Any = None):
    obj = data
    for key in keys:
        if not obj or key not in obj:
            return default
        obj = obj[key]
    return obj

def getTypeOfSale(data):
    keys = ["isPublicSale", "isNotarySale", "isLifeAnnuitySale", "isAnInteractiveSale", 
            "isNewlyBuilt", "isInvestmentProject", "isUnderOption", "isNewRealEstateProject"]
    for key in keys:
        if get_in(data, ["flags", key]) == True:
            return key.replace("is", "")
    return None

def get_property_data(house_index, url):
    response = requests.get(url, headers={"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"})
    parsed_data = {}
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, 'html.parser')
        s = soup.select('iw-load-advertisements')
        if len(s) > 0 and s[0].has_attr(":classified"):
            data = json.loads(s[0].attrs[":classified"])
            
            parsed_data["url"] = url
            parsed_data["bedrooms"] = get_in(data, ["property", "bedroomCount"])
            parsed_data["property_type"] = get_in(data, ["property", "type"])
            parsed_data["property_subtype"] = get_in(data, ["property", "subtype"])
            parsed_data["locality"] = get_in(data, ["property", "location", "locality"])
            parsed_data["postal_code"] = get_in(data, ["property", "location", "postalCode"])
            parsed_data["street"] = get_in(data, ["property", "location", "street"])
            parsed_data["number"] = get_in(data, ["property", "location", "number"])
            parsed_data["box"] = get_in(data, ["property", "location", "box"])
            parsed_data["kitchen"] = get_in(data, ["property", "kitchen", "type"])
            parsed_data["facades"] = get_in(data, ["property", "building", "facadeCount"])
            parsed_data["price"] = get_in(data, ["transaction", "sale", "price"])
            parsed_data["furnished"] = get_in(data, ["transaction", "sale", "isFurnished"])
            parsed_data["terrace"] = get_in(data, ["property", "hasTerrace"])
            parsed_data["terraceSurface"] = get_in(data, ["property", "terraceSurface"])
            parsed_data["fireplace"] = get_in(data, ["property", "fireplaceExists"])
            parsed_data["fireplaceCount"] = get_in(data, ["property", "fireplaceCount"])
            parsed_data["buildingState"] = get_in(data, ["property", "building", "condition"])
            parsed_data["garden"] = get_in(data, ["property", "hasGarden"])
            parsed_data["gardenSurface"] = get_in(data, ["property", "gardenSurface"])
            parsed_data["pool"] = get_in(data, ["property", "hasSwimmingPool"])
            parsed_data["landSurface"] = get_in(data, ["property", "land", "surface"])
            parsed_data["livingArea"] = get_in(data, ["property", "netHabitableSurface"])
            parsed_data["surfaceOfThePlot"] = get_in(data, ["property", "land", "surface"])
            parsed_data["typeOfSale"] = getTypeOfSale(data)
            parsed_data["energy_rating"] = get_in(data, ["property", "Energy Class"])
            
            pool = get_in(data, ["property", "hasSwimmingPool"])
            if pool:
                parsed_data["pool"] = 1
            else:
                parsed_data["pool"] = 0

            kitchen = get_in(data, ["property", "kitchen", "type"])
            if kitchen:
                parsed_data["kitchen"] = 1
            else:
                parsed_data["kitchen"] = 0

            furnished = get_in(data, ["transaction", "sale", "isFurnished"])
            if furnished:
                parsed_data["furnished"] = 1
            else :
                parsed_data["furnished"] = 0

            terrace = get_in(data, ["property", "hasTerrace"])
            if terrace:
                parsed_data["terrace"] = 1
                parsed_data["terraceSurface"] = get_in(data, ["property", "terraceSurface"])
            else:
                parsed_data["terrace"] = 0 
                parsed_data["terraceSurface"] = 0

            fireplace = get_in(data, ["property", "fireplaceExists"])
            if fireplace:
                parsed_data["fireplace"] = 1
                parsed_data["fireplaceCount"] = get_in(data, ["property", "fireplaceCount"])
            else:
                parsed_data["fireplace"] = 0 
                parsed_data["fireplaceCount"] = 0

            garden = get_in(data, ["property", "hasGarden"])
            if garden:
                parsed_data["garden"] = 1
                parsed_data["gardenSurface"] = get_in(data, ["property", "gardenSurface"])
            else:
                parsed_data["garden"] = 0
                parsed_data["gardenSurface"] = 0
    
    return house_index,parsed_data  
    

def save_property_data_2_csv(file_path,fieldnames, properties_data):
    with open(file_path, "w", newline="") as csvfile:
        writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
        writer.writeheader()
        for property_data in properties_data:
            writer.writerow(property_data)

    print("CSV file created successfully.")

def clean_save_dataset(file_path):
    df= pd.read_csv(file_path)
    #drops duplicates
    df.drop_duplicates(subset=['postal_code','street','number','box'], inplace=True)
    #drops the empty rows if there are any.
    df.dropna(how='all',inplace=True)
    #Changing the dtype to category, better for analysis
    df['property_type']=df['property_type'].astype('category')
    df['property_subtype']=df['property_subtype'].astype('category')
    df['locality']=df['locality'].astype('category')
    df['buildingState']=df['buildingState'].astype('category')
    #replace missing values with a None
    df.map(lambda x: None if pd.isna(x) else x)
    # delete the property with 200 bedroom
    df.drop([18860], axis=0, inplace=True)
    df.set_index('house_index', drop=True, inplace=True)
    df.sort_index(inplace=True) 
    df.to_csv("utils/cleaned_dataset.csv",index="house_index")

 


def main():
    program_start = perf_counter()
    property_links = []
    threads = []
    
    url1=f"https://www.immoweb.be/en/search/house-and-apartment/for-sale?countries=BE&isALifeAnnuitySale=false&isNewlyBuilt=false&minConstructionYear=1930&maxConstructionYear=1975&orderBy=relevance"
    url2=f"https://www.immoweb.be/en/search/house-and-apartment/for-sale?countries=BE&isALifeAnnuitySale=false&isNewlyBuilt=false&minConstructionYear=1976&orderBy=relevance"
    urls=[url1,url2]
    for url in urls:
        results = fetch_multiple_pages(url, 1, 334,property_links)  # Fetch pages 1 to 334
        """for page in range(1, 334):
            thread = Thread(target=fetch_links, args=(url,page,property_links))
            threads.append(thread)
            thread.start()
    for thread in threads:
        thread.join()"""
    program_duration = perf_counter() - program_start
    print(f"\nTotal time taken for program: {program_duration:.4f} seconds.")
    print(len(property_links))
    file_path = 'utils/property_links.csv'
    write_links_csv(file_path,property_links)
    
    time.sleep(30)
    with open("utils/property_links.csv", "r") as links:
        urls = [(index, link.strip()) for index, link in enumerate(links)]    

    properties_data = []
    with ThreadPoolExecutor(max_workers=10) as executor:
        futures = [executor.submit(get_property_data, house_index, url) for house_index, url in urls]
        for future in as_completed(futures):
            house_index ,parsed_data = future.result()  
            flattened_data = {"house_index": house_index}
            flattened_data.update(parsed_data)
            properties_data.append(flattened_data)
    fieldnames =properties_data[0].keys()
    output_file_path="utils/all_properties_output.csv"
    save_property_data_2_csv(output_file_path,fieldnames, properties_data)
    clean_save_dataset(output_file_path)
    


if __name__ == "__main__":
    main()

In [ ]:

import time
from threading import Thread
from time import perf_counter
import requests
from bs4 import BeautifulSoup
import json
import csv
from typing import Any

def get_in(data: dict, keys: list, default: Any = None):
    obj = data
    for key in keys:
        if not obj or key not in obj:
            return default
        obj = obj[key]
    return obj

def get_property_data(house_index, url):
    response = requests.get(url, headers={"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36"})
    parsed_data = {}
    if response.status_code == 200:
        soup = BeautifulSoup(response.content, 'html.parser')
        print(soup)
        s = soup.select('iw-load-advertisements')
        if len(s) > 0 and s[0].has_attr(":classified"):
            data = json.loads(s[0].attrs[":classified"])
        
        script_tag = soup.find("script", text=lambda t: t and "let av_items" in t)

        if script_tag:
            script_content = script_tag.string
            start = script_content.find("[{")  # Find the start of the JSON array
            end = script_content.find("}]") + 2  # Find the end of the JSON array
            json_data = script_content[start:end]
            
            # Parse the JSON content
            av_items = json.loads(json_data)
            
            # Extract the energy certificate value
            energy_certificate = av_items[0].get("energy_certificate", "Not found")
            print(f"Energy Certificate: {energy_certificate}")
        else:
            print("av_items script not found!")

            
            print(data)
            parsed_data["bedrooms"] = get_in(data, ["property", "bedroomCount"])
            parsed_data["property_type"] = get_in(data, ["property", "type"])
            parsed_data["property_subtype"] = get_in(data, ["property", "subtype"])
            parsed_data["energy_rating"] = get_in(data2, ["property", "energy_certificate"])

            return parsed_data

house_index = 999
url = "https://www.immoweb.be/en/classified/apartment/for-sale/boncelles/4100/20328855"
energy = get_property_data(house_index, url)

print(energy)